package diago

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsGeneratedSourcePath(t *testing.T) {
	dir := t.TempDir()

	cases := []struct {
		name    string
		file    string
		content string
		want    bool
	}{
		{
			name:    "oapi-codegen filename",
			file:    "api.gen.go",
			content: "package api\n\ntype T struct{}\n",
			want:    true,
		},
		{
			name:    "sqlc filename",
			file:    "models.sql.go",
			content: "package db\n\ntype Row struct{}\n",
			want:    true,
		},
		{
			name:    "generated header marker",
			file:    "schema.go",
			content: "// Code generated by oapi-codegen. DO NOT EDIT.\npackage api\n",
			want:    true,
		},
		{
			name:    "swaggo header with prefix before marker",
			file:    "docs.go",
			content: "//Package docs Code generated by swaggo/swag. DO NOT EDIT\npackage docs\n",
			want:    true,
		},
		{
			name:    "bare do not edit",
			file:    "bare.go",
			content: "// DO NOT EDIT\npackage api\n",
			want:    true,
		},
		{
			name:    "generated by at comment start",
			file:    "proto.go",
			content: "// Generated by protoc. Edit at your own risk.\npackage api\n",
			want:    true,
		},
		{
			name:    "block comment header marker survives inner package line",
			file:    "block.go",
			content: "/*\npackage docs overview\nCode generated by tool. DO NOT EDIT.\n*/\npackage api\n",
			want:    true,
		},
		{
			name:    "prose generated by hand not matched",
			file:    "byhand.go",
			content: "// This file was generated by hand, do not auto-format.\npackage api\n",
			want:    false,
		},
		{
			name:    "prose code generated not matched",
			file:    "prose.go",
			content: "// The code generated below is illustrative.\npackage api\n",
			want:    false,
		},
		{
			name:    "marker after package is ignored",
			file:    "late.go",
			content: "package api\n\n// Code generated by hand. DO NOT EDIT.\n",
			want:    false,
		},
		{
			name:    "hand written file",
			file:    "service.go",
			content: "package api\n\nfunc Do() {}\n",
			want:    false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, tc.file)
			if err := os.WriteFile(path, []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			if got := isGeneratedSourcePath(path); got != tc.want {
				t.Errorf("isGeneratedSourcePath(%s) = %v, want %v", tc.file, got, tc.want)
			}
		})
	}
}

func TestIsIgnoredSourcePath(t *testing.T) {
	dir := t.TempDir()

	cases := []struct {
		name    string
		content string
		want    bool
	}{
		{"directive no space", "//diago:ignore\npackage api\n", true},
		{"directive with space", "// diago:ignore\npackage api\n", true},
		{"directive with reason", "//diago:ignore vendored upstream copy\npackage api\n", true},
		{"single-line block comment directive", "/*diago:ignore*/\npackage api\n", true},
		{"directive after package ignored", "package api\n\n//diago:ignore\n", false},
		{"not a directive", "//diago:ignored\npackage api\n", false},
		{"no directive", "package api\n\nfunc Do() {}\n", false},
	}
	for i, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, fmt.Sprintf("f%d.go", i))
			if err := os.WriteFile(path, []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			if got := isIgnoredSourcePath(path); got != tc.want {
				t.Errorf("isIgnoredSourcePath = %v, want %v", got, tc.want)
			}
		})
	}
}

func TestFilterSkippedFindings(t *testing.T) {
	dir := t.TempDir()
	write := func(name, content string) string {
		path := filepath.Join(dir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		return path
	}

	genPath := write("api.gen.go", "package api\n")
	ignorePath := write("vendored.go", "//diago:ignore\npackage api\n")
	srcPath := write("service.go", "package api\n")

	findings := []ASTFinding{
		{Rule: "modernize", File: genPath, Line: 12},
		{Rule: "modernize", File: ignorePath, Line: 3},
		{Rule: "modernize", File: srcPath, Line: 8},
		{Rule: "modernize", File: "service.go", Line: 9}, // relative, resolved against workDir
		{Rule: "magic-number", File: ""},                 // no file: kept
	}

	t.Run("default drops generated and ignored", func(t *testing.T) {
		kept := filterSkippedFindings(findings, dir, false)
		if len(kept) != 3 {
			t.Fatalf("expected 3 kept, got %d: %+v", len(kept), kept)
		}
		for _, f := range kept {
			if f.File == genPath || f.File == ignorePath {
				t.Errorf("skipped file finding was not filtered: %+v", f)
			}
		}
	})

	t.Run("include-generated keeps generated but still drops ignored", func(t *testing.T) {
		kept := filterSkippedFindings(findings, dir, true)
		var sawGen, sawIgnore bool
		for _, f := range kept {
			switch f.File {
			case genPath:
				sawGen = true
			case ignorePath:
				sawIgnore = true
			}
		}
		if !sawGen {
			t.Error("generated finding should be kept when includeGenerated is set")
		}
		if sawIgnore {
			t.Error("//diago:ignore finding must be dropped even when includeGenerated is set")
		}
	})
}

func TestGeneratedFilesDoNotInflateLargePackageTotals(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/size\n\ngo 1.22\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	generatedDir := filepath.Join(dir, "generatedsql")
	handwrittenDir := filepath.Join(dir, "handwritten")
	for _, path := range []string{generatedDir, handwrittenDir} {
		if err := os.Mkdir(path, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	for i := range 51 {
		var generated strings.Builder
		generated.WriteString("package generatedsql\n")
		for j := range 10 {
			fmt.Fprintf(&generated, "func Query%d_%d() {}\n", i, j)
		}
		generatedName := filepath.Join(generatedDir, fmt.Sprintf("query_%02d.sql.go", i))
		if err := os.WriteFile(generatedName, []byte(generated.String()), 0o644); err != nil {
			t.Fatal(err)
		}
		handwritten := fmt.Sprintf("package handwritten\nfunc Part%d() {}\n", i)
		handwrittenName := filepath.Join(handwrittenDir, fmt.Sprintf("part_%02d.go", i))
		if err := os.WriteFile(handwrittenName, []byte(handwritten), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	findings, err := AnalyzeAST(dir, "./...")
	if err != nil {
		t.Fatal(err)
	}
	largePackages := map[string]bool{}
	for _, finding := range findings {
		if finding.Rule == "large-package" {
			largePackages[finding.Package] = true
		}
	}
	if largePackages["example.com/size/generatedsql"] {
		t.Fatalf("generated-only sqlc package counted as large: %+v", findings)
	}
	if !largePackages["example.com/size/handwritten"] {
		t.Fatalf("handwritten large package was not reported: %+v", findings)
	}
}
