package diago

import (
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedSourcePath(t *testing.T) {
	dir := t.TempDir()

	cases := []struct {
		name    string
		file    string
		content string
		want    bool
	}{
		{
			name:    "oapi-codegen filename",
			file:    "api.gen.go",
			content: "package api\n\ntype T struct{}\n",
			want:    true,
		},
		{
			name:    "sqlc filename",
			file:    "models.sql.go",
			content: "package db\n\ntype Row struct{}\n",
			want:    true,
		},
		{
			name:    "generated header marker",
			file:    "schema.go",
			content: "// Code generated by oapi-codegen. DO NOT EDIT.\npackage api\n",
			want:    true,
		},
		{
			name:    "marker after package is ignored",
			file:    "late.go",
			content: "package api\n\n// Code generated by hand. DO NOT EDIT.\n",
			want:    false,
		},
		{
			name:    "hand written file",
			file:    "service.go",
			content: "package api\n\nfunc Do() {}\n",
			want:    false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, tc.file)
			if err := os.WriteFile(path, []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}
			if got := isGeneratedSourcePath(path); got != tc.want {
				t.Errorf("isGeneratedSourcePath(%s) = %v, want %v", tc.file, got, tc.want)
			}
		})
	}
}

func TestFilterGeneratedFindings(t *testing.T) {
	dir := t.TempDir()

	genPath := filepath.Join(dir, "api.gen.go")
	if err := os.WriteFile(genPath, []byte("package api\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	srcPath := filepath.Join(dir, "service.go")
	if err := os.WriteFile(srcPath, []byte("package api\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	findings := []ASTFinding{
		{Rule: "modernize", File: genPath, Line: 12},
		{Rule: "modernize", File: srcPath, Line: 8},
		{Rule: "modernize", File: "service.go", Line: 9}, // relative, resolved against workDir
		{Rule: "magic-number", File: ""},                 // no file: kept
	}

	kept := filterGeneratedFindings(findings, dir)
	if len(kept) != 3 {
		t.Fatalf("expected 3 findings kept, got %d: %+v", len(kept), kept)
	}
	for _, f := range kept {
		if f.File == genPath {
			t.Errorf("generated file finding was not filtered: %+v", f)
		}
	}
}
